### ISSUE TITLE
Opens AirDrop window behind everything

### ISSUE THREAD

**Issue by jeffThompson** [mattt/terminal-share#11]
What a rad and useful project – thank you!

One kind of frustrating thing I noticed is that the AirDrop window opens behind everything, meaning you have to hide the Terminal first to send the file. Dunno how this works behind the scenes but would love to see that (minor) update!

**Comment by alanhg** [comment]
Indeed, this is a problem

![image](https://user-images.githubusercontent.com/9245110/102704274-57d42700-42b4-11eb-8db8-5d9b36407df4.png)

**Comment by alanhg** [comment]
@mattt Is there any way to solve this problem?

Thank you.

**Comment by alanhg** [comment]
I chose to use the AppleScript action menu to fix it

```
tell application "System Events"
	tell process "Chrome"
		set frontmost to true
		
		# File=>Share=>AirDrop
		click menu item "AirDrop" of menu of menu item "Share" of menu "File" of menu bar 1
	end tell
end tell
```

**Comment by RichardBronosky** [comment]
Ugh! This is a nasty bug! I use the swipe gesture for "Mission Control" and locate the share window. But, even clicking it doesn't work because it is fixed to the bottom of the stack. So, I drag it to the ⨁ in the upper right corner to move the share window to its own "Desktop" and there I can actually interact with it.
